name: Deploy Frontend via SCP

on:
  workflow_call:
    secrets:
      host:
        required: true
      username:
        required: true
      key:
        required: true
      passphrase:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: dist

      - name: Copy artifact to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          key: ${{ secrets.key }}
          passphrase: ${{ secrets.passphrase }}
          source: "dist/*"
          target: "frontend/"
          strip_components: 1